# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Panotools-Script
version:      0.19
version_from: lib/Panotools/Script.pm
installdirs:  site
requires:
    bytes:                         0
    File::Copy:                    1
    File::Spec:                    0.8
    File::Temp:                    0.1
    Getopt::Long:                  2
    GraphViz:                      1
    Image::ExifTool:               6
    Image::Size:                   2.9
    Math::Trig:                    0.1
    Pod::Usage:                    1
    Storable:                      2
    Test::More:                    0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
