--- #YAML:1.0
name:               Panotools-Script
version:            0.26
abstract:           Panorama Tools scripting
author:
    - Bruno Postle <bruno@postle.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    bytes:            0
    File::Copy:       1
    File::Spec:       0.8
    File::Temp:       0.1
    Getopt::Long:     2
    Getopt::Std:      1
    Image::ExifTool:  6
    Image::Size:      2.9
    LWP::UserAgent:   0
    Math::Trig:       0.1
    Pod::Usage:       1
    Storable:         2
    Test::More:       0.1
    URI:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
