# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Panotools-Script
version:      0.07
version_from: lib/Panotools/Script.pm
installdirs:  site
requires:
    Image::Magick:                 5
    Math::Matrix:                  0.4
    Storable:                      2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
